import type { CheckStatus } from '@digitx/core';

export type Locale = 'zh' | 'en';

export const copy = {
  zh: {
    refresh: '刷新数据',
    language: 'English',
    languageShort: 'EN',
    lightMode: '切换到浅色主题',
    darkMode: '切换到深色主题',
    github: '查看 GitHub 项目',
    eyebrow: 'DIGITX / 数字域名验证工作台',
    heroTitle: '让稀有数字，自己说话。',
    heroDescription: '聚合高分数字组合，以 DNS 和 WHOIS 双通道完成验证，专注留下真正值得关注的域名。',
    verificationPath: '验证路径',
    dns: 'DNS 筛选',
    whois: 'WHOIS 确认',
    availability: '可用性结果',
    available: '可注册',
    checked: '已验证',
    registered: '已注册',
    queued: '待验证',
    searchPlaceholder: '搜索数字、模式或描述',
    status: '状态',
    allStatuses: '全部',
    length: '位数',
    category: '模式',
    anyLength: '任意长度',
    allPatterns: '所有模式',
    showing: '显示',
    domains: '个域名',
    tableDomain: '域名',
    tableLength: '位数',
    tablePattern: '模式',
    tableScore: '得分',
    tableStatus: '状态',
    tableAction: '操作',
    top: '高分',
    register: '去注册',
    detail: '详情',
    emptyTitle: '没有匹配的域名',
    emptyDescription: '调整筛选条件，或清除搜索关键词后重试。',
    detailEyebrow: '域名详情',
    detailDescription: '当前评分、验证状态与 WHOIS 记录。',
    close: '关闭',
    score: '质量得分',
    pattern: '主分类',
    tags: '模式标签',
    scoreBreakdown: '计分明细',
    currentStatus: '当前状态',
    checkedAt: '最后核查',
    whoisDetail: 'WHOIS 验证记录',
    noDetail: '暂无详细验证记录',
    goRegister: '注册此域名',
    unavailableMessage: '该域名已注册，可持续关注其释放状态。',
    footer: '数字域名验证工作台 · 由 Cloudflare Pages 与 Workers 提供支持。',
    showingRange: (start: number, end: number, total: number) => `显示 ${start} - ${end} / 共 ${total} 条`,
    perPage: '条/页',
    previousPage: '上一页',
    nextPage: '下一页'
  },
  en: {
    refresh: 'Refresh data',
    language: '中文',
    languageShort: '中',
    lightMode: 'Switch to light theme',
    darkMode: 'Switch to dark theme',
    github: 'View project on GitHub',
    eyebrow: 'DIGITX / NUMERIC DOMAIN WORKBENCH',
    heroTitle: 'Let rare numbers speak for themselves.',
    heroDescription: 'High-signal numeric patterns, verified through DNS and WHOIS, so the domains worth watching stay in view.',
    verificationPath: 'Verification path',
    dns: 'DNS filter',
    whois: 'WHOIS check',
    availability: 'Availability',
    available: 'Available',
    checked: 'Verified',
    registered: 'Registered',
    queued: 'Queued',
    searchPlaceholder: 'Search number, pattern, or description',
    status: 'Status',
    allStatuses: 'All',
    length: 'Length',
    category: 'Pattern',
    anyLength: 'Any length',
    allPatterns: 'All patterns',
    showing: 'Showing',
    domains: 'domains',
    tableDomain: 'Domain',
    tableLength: 'Length',
    tablePattern: 'Pattern',
    tableScore: 'Score',
    tableStatus: 'Status',
    tableAction: 'Action',
    top: 'Top',
    register: 'Register',
    detail: 'Details',
    emptyTitle: 'No matching domains',
    emptyDescription: 'Adjust the filters or clear the search term to try again.',
    detailEyebrow: 'Domain details',
    detailDescription: 'Current score, verification status, and WHOIS record.',
    close: 'Close',
    score: 'Quality score',
    pattern: 'Primary category',
    tags: 'Pattern tags',
    scoreBreakdown: 'Score breakdown',
    currentStatus: 'Current status',
    checkedAt: 'Last checked',
    whoisDetail: 'WHOIS verification record',
    noDetail: 'No verification record yet',
    goRegister: 'Register this domain',
    unavailableMessage: 'This domain is registered. Watch for a future release.',
    footer: 'Numeric domain verification workbench · Powered by Cloudflare Pages and Workers.',
    showingRange: (start: number, end: number, total: number) => `Showing ${start}-${end} of ${total}`,
    perPage: 'per page',
    previousPage: 'Previous',
    nextPage: 'Next'
  }
} as const;

export function statusLabel(locale: Locale, status: CheckStatus): string {
  const labels = {
    available: copy[locale].available,
    registered: copy[locale].registered,
    unchecked: copy[locale].queued,
    checking: copy[locale].queued,
    error: locale === 'zh' ? '验证异常' : 'Verification error'
  } as const;

  return labels[status];
}
